---
title: "data_from_web"
author: "Lyuou Zhang"
date: "10/22/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)


```


```{r cars}

url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml <- read_html(url)

drug_use_xml

table_marj <- drug_use_xml %>% 
  html_nodes(css = 'table') %>% 
  .[[1]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()

data_marj <- table_marj %>% 
  select(-contains('P Value')) %>% 
  gather(key = key, value = percent, -State) %>% 
  separate(key, into = c('age', 'year'), sep = '')


```


```{r hp}
hpsaga_html = read_html("https://www.imdb.com/list/ls000630791/")

title_vec <- hpsaga_html %>% 
  html_nodes('.lister-item-header a') %>% 
  html_text()

gross_rev_vec <- hpsaga_html %>% 
  html_nodes('.text-muted .ghost~ .text-muted+ span') %>% 
  html_text()

runtime_vec <- hpsaga_html %>% 
  html_nodes('.runtime') %>% 
  html_text()

hpsaga_df <- tibble(
  title = title_vec,
  rev = gross_rev_vec,
  runtime = runtime_vec
)

```

```{r}
dynamite_html <- read_html('https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1')

review_titles = dynamite_html %>% 
  html_nodes('#cm_cr-review_list .review-title') %>% 
  html_text()

review_stars <- dynamite_html %>% 
  html_nodes('#cm_cr-review_list .review-rating') %>% 
  html_text()

review_text <- dynamite_html %>% 
  html_nodes('.review-data:nth-child(4)') %>% 
  html_text()

reviews <- tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

  


```

```{r}
nyc_water <- GET('https://data.cityofnewyork.us/resource/waf7-5gvc.csv') %>% 
  content('parsed')

nyc_water <- GET('https://data.cityofnewyork.us/resource/waf7-5gvc.json') %>% 
  content('text') %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()

poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name

```




